### ISSUE TITLE
Bug in categories filtering with only one level

### ISSUE THREAD

**Issue by erinliu1** [MIT-CAVE/cave_static#113]
There is a bug when the categories only has one level, as the filter ability renders incorrectly (see below). But when you add a secondary level, it renders properly.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/90478485/211055507-7729c521-3641-4008-8c3c-dc57276c0caf.png">
<img width="624" alt="image (1)" src="https://user-images.githubusercontent.com/90478485/211055847-01101f10-3445-4a34-8dc9-65f48aee961b.png">

**Comment by connor-makowski** [comment]
@luisvasq or @mrkwanzaa Do either of you want to pick this one up?

**Comment by mrkwanzaa** [comment]
I'm happy to check it out
