### ISSUE TITLE
For radio variants, the value should still be a list for consistency.

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#114]
The radio button should follow the same logic as normal. If a new item is selected, then the list will be just the new item.

**Comment by luisvasq** [comment]
Similar case with a single-selection `'dropdown'`. I guess you wouldn't care if we handle it as a simple string value on front-end. If that's the case, are you okay with allowing an **optional** string value for `'radio'` and `'dropdown'` on API side?

**Comment by luisvasq** [comment]
In the meantime, added support for both types.

**Comment by connor-makowski** [comment]
For consistency, lets just aim to keep all of these as a list of strings. This offers the most clarity for an API designer. It also allows the easiest switch between variants. I expect this variant switch to be common during rapid prototyping.
