### ISSUE TITLE
Map hard to interact with on cave touch screens

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#142]
@mitrussell Can you clarify for @mrkwanzaa what is going on here?

**Comment by mitrussell** [comment]
Next time you are at CTL I can show you, but it is difficult to select an icon that is over a selectable geo area. Touch is not intuitive and often needs multiple tries to get correct.

From: Connor Makowski ***@***.***>
Date: Wednesday, January 25, 2023 at 4:32 PM
To: MIT-CAVE/cave_static ***@***.***>
Cc: Tim Russell ***@***.***>, Mention ***@***.***>
Subject: [MIT-CAVE/cave_static] Map hard to interact with on cave touch screens (Issue #142)

@mitrussell<https://github.com/mitrussell> Can you clarify for @mrkwanzaa<https://github.com/mrkwanzaa> what is going on here?

**Comment by connor-makowski** [comment]
I was able to recreate some of these issues on a windows touch device. I think we could solve some of these issues by adding an invisible touch area over each icon.

Some of the other issues might be related to a hover feature of windows touch.

**Comment by mrkwanzaa** [comment]
The above commit fixes the issues with nodes being difficult to select due to transparency. The hover issue is still present, and I think a problem with the input. One option here is to create a "touch mode" where hover is considered the same as click.
