### ISSUE TITLE
The Use Effect for get_assocaited_session_data fires 2x on initial session load

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#145]

**Comment by mrkwanzaa** [comment]
Looks like this is due to the use of [react strict mode](https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode/61897567#61897567). This should be disabled in production builds.

**Comment by connor-makowski** [comment]
That is an odd bug. Lets close this for now.
