### ISSUE TITLE
Categorical Coloring for Geos does not work unless all items in a layer have that categorical data.

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#163]
This may extend beyond Geos into Nodes and arcs, but I did not test that.

Essentially if you are coloring by some value but one value in geos.data is missing that value, then the layer bugs (not an app crash) and does not show.

Work with @luisvasq to avoid any crazy merge conflicts.

**Comment by luisvasq** [comment]
If this is only geos, there might be a few conflicts if auto-merge doesn't get it right when I merge, but I'll keep my work on nodes and we should be fine.
