### ISSUE TITLE
Bump to React 18

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#22]

**Comment by mrkwanzaa** [comment]
@connor-makowski the latest version of mui (5.10.2) doesn't support React 18 yet. We might want to wait on this until it is supported.

**Comment by connor-makowski** [comment]
Okay lets wait then.

**Comment by connor-makowski** [comment]
Moving this over to @luisvasq to open up bandwidth for @mrkwanzaa

**Comment by luisvasq** [comment]
Closed by d0f4f6fd272e34e37f300b6617e64872b9850d73.
