### ISSUE TITLE
Change way sessions are named in KPI Chart

### ISSUE THREAD

**Issue by mitrussell** [MIT-CAVE/cave_static#223]
In the dashboard, as you create a KPI table and select the sessions, the sessions are named “Personal (username)->Session Name”. When looking at the resulting table, the session names are almost ALWAYS cut off because they are too long.
Would it be possible to list the session name first and then the “->Personal (username)” part second?

![Image](https://user-images.githubusercontent.com/47668639/235712966-120fc754-3940-4a7f-a45e-8e74eef6a60f.png)

**Comment by connor-makowski** [comment]
Closing this as a wontfix (for now).
