### ISSUE TITLE
`textarea` causes MUI render loop

### ISSUE THREAD

**Issue by maxtkc** [MIT-CAVE/cave_static#231]
Not exactly sure why, but when the app tries to render a `textarea`, it causes a MUI render loop. When I remove it from the api, the error goes away. I haven't investigated further, but it happens with the `textAreaInputExample`.

![image](https://github.com/MIT-CAVE/cave_static/assets/18196879/adbb2cde-9731-4cb7-a43a-86d26bda26a4)

**Comment by luisvasq** [comment]
Thanks, @maxtkc! I'll take a look.
