### ISSUE TITLE
Add new projection options

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#258]
Ideally we would offer a variety of projections, but we should add projections that support views near the poles like a globe projection or a better area weighted projection with vertical scroll wrapping.

**Comment by connor-makowski** [comment]
It is possible, that this will require breaking the api.

**Comment by mitrussell** [comment]
I saw this example a few days ago. https://uwdata.github.io/mosaic/examples/earthquakes.html 
I wanted to mention it as an alternative approach.

**Comment by connor-makowski** [comment]
Some other ideas we have considered:
https://echarts.apache.org/examples/en/editor.html?c=lines3d-flights&gl=1
https://www.mapbox.com/blog/globe-view
https://deck.gl/docs/api-reference/core/globe-view

**Comment by maxtkc** [comment]
#273
