### ISSUE TITLE
Possible feature to allow exporting the session data from an app.

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#259]

**Comment by connor-makowski** [comment]
@brianzheng205 I am currently working on a new static data backed persistent cache. See: https://github.com/MIT-CAVE/cave_app/commit/7cd7278487acaa9d906154bc41e8e524ce562970

From a Django perspective, I am still working on this and plan to overhaul the way we cache queries and access the cache (plus backup). For downloads, we would first need to manually backup the current session and then return the link to download the session data items. Ill think about this as I implement the more efficient overall framework.

**Comment by brianzheng205** [comment]
@connor-makowski @mrkwanzaa cave static https://github.com/MIT-CAVE/cave_static/pull/563 and cave app https://github.com/MIT-CAVE/cave_app/pull/176 PRs have been created

**Comment by mrkwanzaa** [comment]
Nice work, very clean. I've merged these PRs
