### ISSUE TITLE
Using `TbBuildingWarehouse` as a node icon breaks other icons on the map

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#268]
Add `TbBuildingWarehouse` as an icon for a node and reset your data. 

The other nodes then bug out when using the app.

**Comment by connor-makowski** [comment]
This should be fixed in 1.5.2

**Comment by mrkwanzaa** [comment]
This is fixed by the above commit and the fix is merged into 1.6.0-dev and 2.0.0-dev
