### ISSUE TITLE
Investigate using alternatives to mapbox

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#28]

**Comment by maxtkc** [comment]
what are the main issues/goals for this?

**Comment by connor-makowski** [comment]
Ideally, we would have the ability to swap out map packages and keep everything working. This may not be reasonably possible or there may be restrictions, like staying within the deck GL framework.

**Comment by connor-makowski** [comment]
This ticket is more investigative as to if it is reasonably possible and if we want to add support for multiple mapping packages.

**Comment by maxtkc** [comment]
At first glance, it seems that the easiest alternatives, staying within [DeckGL](https://deck.gl/), would be [ArcGIS](https://www.arcgis.com/index.html), [Carto](https://carto.com/), [Google 3D Tiles](https://developers.google.com/maps/documentation/tile/3d-tiles), and [Google Maps](https://www.google.com/maps)
