### ISSUE TITLE
3D arcs not working

### ISSUE THREAD

**Issue by mrkwanzaa** [MIT-CAVE/cave_static#289]
Looks like we still need to implement these on the new maps

**Comment by mrkwanzaa** [comment]
After further investigation, it appears that 3d arcs aren't natively supported in MapBox GL. I think its worth discussing if we need these now that we support globe views, as they will probably be difficult to implement.

**Comment by mrkwanzaa** [comment]
@connor-makowski Do you know if these are still important for our partners (or us)?

**Comment by connor-makowski** [comment]
I will go ahead and say yes. But not if it is too expensive time wise to implement.
