### ISSUE TITLE
Create a 'demo' settings key.

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#295]
Something that rotates between views (dashboards and maps) and offers some flexibility on map motions (eg for globe spinning). Maybe include some timing pieces here too.

**Comment by mrkwanzaa** [comment]
I've added a simple demo mode that can be toggled on in the app settings pane that cycles through all views (dashboards, maps, kpis) spending more time on maps, rotating them. @connor-makowski Can you let me know if we want to offer more customization through the api, or keep it simple

**Comment by connor-makowski** [comment]
We might want some customization here. Mostly around timings and map scroll speed.

**Comment by mrkwanzaa** [comment]
Sounds good. I also talked to Matthias and he wanted to ability to skip specified dashboards/maps. I'll add these into the settings key and push a final version with docs later today
