### ISSUE TITLE
Lat Long Picker Prop

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#299]

**Comment by mrkwanzaa** [comment]
Here's what I'm thinking for the API for this prop:

```
"latLongProp": {
                     "name": "Lat/Lng Prop",
                     "type": "latlng",
                     "help": "Some help",
               },
```
with value:
```
"latLongProp": { "latitude": 34.33, "longitude": 43.44 },
```

This value matches with the node location dictionary, keeping things consistent and also allowing easy node relocations. @connor-makowski What are your thoughts here? We could keep things smaller by just using a length two list, but we lose the consistency with nodes.

**Comment by connor-makowski** [comment]
Lets aim to type them as `coordinate` props.

For a pane prop, this structure makes sense. For a mapFeature valueList, I could see this being costly.

Thoughts on doing something clever here like specifying a value key for lat and a value key for long? Then you would have two values or valuelists per coordinate prop. Naturally we would use the same process in the panes prop structure.

**Comment by mrkwanzaa** [comment]
After further discussion, we've decided that the value will instead be a simple list of lists to contain data size. ie
```
"latLongProp": [34.33, 43.44]
```

**Comment by connor-makowski** [comment]
For paths, we use long then lat.

Lets go ahead and aim to make this a lngLat prop and format the list sequence accordingly.

**Comment by connor-makowski** [comment]
This prop will need to have the ability to pick the long and lat by clicking on a map. It should also have the ability to manually input each. The original component will likely have a button that says, pick a point on the map and also has 2 input boxes for each input. Once someone clicks on the map, the input boxes will be updated accoringly.

**Comment by connor-makowski** [comment]
Nice job @aiizhao ! I know we have 3 projects currently planning on using this.

**Comment by connor-makowski** [comment]
Closing with https://github.com/MIT-CAVE/cave_static/pull/495

**Comment by connor-makowski** [comment]
Added validator support: https://github.com/MIT-CAVE/cave_utils/commit/d05c52b55ebe9019888bb4ded5a8b246eca26d66

Note: This still requires a bit of modification to unify the data structure for the coordinate prop

**Comment by mrkwanzaa** [comment]
Closing with  #508
