### ISSUE TITLE
lockedLayout doesn't work

### ISSUE THREAD

**Issue by mrkwanzaa** [MIT-CAVE/cave_static#359]
For pages, setting `lockedLayout` to true doesn't prevent the editing of the page in any way. Charts can still be added, removed, and edited.

**Comment by luisvasq** [comment]
It's working for me, but I think there's an issue re-rendering the default data loaded from the API. I remember sometimes having to refresh after reloading defaults. I'm going to look into it.

**Comment by luisvasq** [comment]
I think the sync "issue" that also happened to me before is just the Dashboards toggle that is off. :smile:

**Comment by mrkwanzaa** [comment]
Working for me now too. Maybe it was a sync issue that I missed. Thanks for checking it out
