### ISSUE TITLE
Support N Level groupings UI for relevant charts.

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#384]

**Comment by mrkwanzaa** [comment]
@luisvasq I don't think there are any other charts where we'll want nLevel grouping, but if you think of some please let me know. I believe Connor said you'll be handling the UI, so I haven't implemented that at all yet.

As far as implementation goes, the groupingId and groupedOutputDataId lists in each chart can be extended for any amounts of groups for the sunburst, treemap, and table charts. Finally, the chartMaxGrouping value in enums.js is currently set to 2 for these charts. This is only used for how many groups to keep when switching charts, but feel free to raise this value and tie more functionality in here.

Here is an example for a 3-level grouped table in the api
```
{
    "variant": "table",
    "groupingLevel": ["location", "size", "location"],
    "lockedLayout": True,
    "groupingId": ["country", "sku", "state"],
    "statAggregation": "mean",
    "groupedOutputDataId": "locationGroup",
    "statId": "numericExampleCalculationStat",
},
```

**Comment by luisvasq** [comment]
Thank you, @mrkwanzaa. I'll take a look early next week and let you know if anything comes up.
