### ISSUE TITLE
Icons flipping between inverted and regular color on maps at different zoom levels.

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#393]
![Screenshot from 2023-10-20 16-31-37](https://github.com/MIT-CAVE/cave_static/assets/32932187/b7b0b0c7-eb3f-40f9-b927-2c9c539038af)

Sometimes they disappear too.

**Comment by mrkwanzaa** [comment]
I'm able to recreate the disappearance, which I'm working on. However, I can't recreate this inversion. Can you describe exactly what you're doing to see this?

**Comment by mrkwanzaa** [comment]
Looks like the disappearance is a known mapbox issue (https://github.com/mapbox/mapbox-gl-js/issues/12645). The fix for this is replacing line 268 in map.js with 
```
projection={zoom < 6 ? mapProjection: "mercator"}
```

However, this causes all map tiles to reload, which I believe is an even worse visual experience. Still no idea where the inversion is coming from, but it could be related

**Comment by connor-makowski** [comment]
In this case, I can get various color issues by moving, zooming, pan and tilt.

**Comment by mrkwanzaa** [comment]
Can you give me more details about how you're finding these issues(which example, is chrome updated, using touch, anything else)? I'm still not able to recreate anything other than the disappearance issue discussed above.

**Comment by connor-makowski** [comment]
I am seeing this in `kitchen_sink.py` and `map_feature_nodes.py`. Essentially when I pan the map or zoom in and out the icons do some odd things.

**Comment by connor-makowski** [comment]
https://github.com/MIT-CAVE/cave_static/assets/32932187/d953f678-534e-4b4b-a5cc-68b6df1ddb1b

**Comment by connor-makowski** [comment]
Just tried. Still an issue for me.

**Comment by connor-makowski** [comment]
Tried updating node and npm and reinstalling deps. No love there either.

**Comment by mrkwanzaa** [comment]
Hm, I just updated to the same versions for node & npm with reinstalled deps and I'm still not able to recreate this.

**Comment by connor-makowski** [comment]
Yeah. @luisvasq said he could also not recreate this issue. Not sure what is going on. My chrome is up to date as well.

**Comment by connor-makowski** [comment]
No love from cache clear either by the way (tried that right away).

**Comment by mrkwanzaa** [comment]
Do you think it could be a driver issue? I had Max try too and he also couldn't recreate the issue.

**Comment by connor-makowski** [comment]
Cant reproduce on any other machine except my Ubuntu Desktop with RTX3090. Closing as a non issue for the time being.
