### ISSUE TITLE
Race event when hosting the cave_app causes the app page to crash on normal `reload` but not `clear cache and hard reload`

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#42]

**Comment by connor-makowski** [comment]
Thought this was specific to daphne, but it appears to be general to django for us at this point.

**Comment by mrkwanzaa** [comment]
@connor-makowski I've fixed this in 0.3.0-dev. Do you want me to add a hotfix branch 0.2.1, or just keep the fix in 0.3.0-dev?

**Comment by connor-makowski** [comment]
0.3.x is fine
