### ISSUE TITLE
Add new `'listCheckbox'` and `'listToggle'` variants to the `'selector'` prop

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#425]
These variants will follow the existing list UI in the global outputs draggable.

**Comment by connor-makowski** [comment]
@aiizhao Assigning this to you so you can get working it.

**Comment by connor-makowski** [comment]
@luisvasq can you check out https://github.com/MIT-CAVE/cave_static/pull/451

**Comment by connor-makowski** [comment]
After more thought, I think we might just nix this entire function. I loved the work, but we want the UX to be modular at the prop level and not inside of the prop.
