### ISSUE TITLE
Add `'comboboxMulti'` variant to the `'selector'` prop

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#426]
Each selected item should be placed below the input combobox as a removable tag item.

**Comment by connor-makowski** [comment]
Re assigning to Alice as @luisvasq is pretty backed up on other bug fixes and issues.

**Comment by connor-makowski** [comment]
Essentially, this should allow a multi select process alongside of a combobox.

**Comment by connor-makowski** [comment]
Maybe something like: 

Feel free to take liberties on the UI to match our standard styles.

![20240220_162457](https://github.com/MIT-CAVE/cave_static/assets/32932187/fb8c68f5-5fcc-47c7-8fc2-9d59a7de0b63)

**Comment by luisvasq** [comment]
This has been reviewed and merged by @mrkwanzaa. Closing this one.
