### ISSUE TITLE
Clean up UI for new flilters

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#432]
Given the new map and dashboard filters, clean up the UI/UX. I am not sure what I want, but I trust that you can make it pop.

@mrkwanzaa tagging you here so you can work with Luis. @luisvasq there are a few remaining functinal bugs here that Willem is sorting out. Try not to stomp on each others work.

**Comment by mrkwanzaa** [comment]
Hey Luis, the current UI code is pretty messy (sorry about that), so please feel free to reach out if things aren't making sense.

**Comment by luisvasq** [comment]
@mrkwanzaa, no worries. Thank you!

**Comment by luisvasq** [comment]
Reopening to bring back map filters.
