### ISSUE TITLE
Add 3D map support.

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#434]

**Comment by brianzheng205** [comment]
Example in cave_app is done: https://github.com/MIT-CAVE/cave_app/pull/171
MVP in cave_static https://github.com/MIT-CAVE/cave_static/pull/547 is done and only missing node/sprite rotations.

**Comment by mrkwanzaa** [comment]
I've merged the above PRs so I'm going to close this.
