### ISSUE TITLE
Implement UI/UX for nested logic groups in `GridFilter`

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#458]

**Comment by connor-makowski** [comment]
@luisvasq when you get a chance, can you check this out?

**Comment by connor-makowski** [comment]
Are there any breaking changes here or any reasons why we cant bump this back to 2.3.0 since it isnt released yet.

**Comment by katherineyli** [comment]
@connor-makowski @luisvasq I've implemented the new bulk edit/save model, let me know what you guys think. I know the colored lines for depth aren't exactly ideal looking right now, but I'll continue to work on that as well.
