### ISSUE TITLE
Clean up UI for Chart headers

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#47]
Lets work on improving the chart header bar UI.

**Comment by connor-makowski** [comment]
@luisvasq I want you to work with @Visionnaire19 to scope out improvements and help him get them in place.

@luisvasq lets be strict on code style and quality. It is okay to have him work through the issues a few times until both the UI and code look good. This is a good learning opportunity for @Visionnaire19

**Comment by luisvasq** [comment]
Sounds like a good plan.

@Visionnaire19 Today, I'll change a few things on the dashboard, and then we can have a meeting to coordinate some subtasks related to this issue.

**Comment by connor-makowski** [comment]
@luisvasq You can take this full steam as @Visionnaire19 will be switching over to solo issues.
