### ISSUE TITLE
Map Legend toggles should automatically hide/show arc, node, or geo details

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#471]

**Comment by connor-makowski** [comment]
@Luis can you add some clarifications here as to the expected behavior vs the actual behavior.

**Comment by luisvasq** [comment]
Sure thing. I created this issue based on a conversation we had a while ago. The idea is to collapse/expand a legend group _row_ when its toggle is on/off. When the last active toggle in the group is switched off, the entire legend group will be collapsed. For example:

1. All toggles are on:
![1](https://github.com/MIT-CAVE/cave_static/assets/7025739/b900820a-9ec7-4e9a-b47f-e7a9829eed77)

2. Flow Type 1 is switched off, collapsing the row:
![2](https://github.com/MIT-CAVE/cave_static/assets/7025739/5f4f2fd9-fcd2-49fd-a754-8b993e96110c)

3. Flow Type 2 is switched off, collapsing both Flow Type 2 and Legend Group A:
![3](https://github.com/MIT-CAVE/cave_static/assets/7025739/abf0aa27-7a51-4ee8-8cf2-97f356f34a34)

**Comment by katherineyli** [comment]
@luisvasq @connor-makowski Fixed!

**Comment by connor-makowski** [comment]
Can you create a pr @katherineyli

**Comment by connor-makowski** [comment]
Nice Job. Closing after the merge of #521
