### ISSUE TITLE
When sorting / ordering groupings, parent levels should be respected.

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#475]
Consider the following example:

Dates: Jan 01, Jan 02, Feb 01, Feb 02

With Month being a parent of Date.

Assuming I order:

Month: Jan, Feb 
Date: 01, 02

I would expect any chart with group by Date to show an axis of Jan 01, Jan 02, Feb 01, Feb 02 In that order.

Currently this would output: Feb 01, Jan 01, Feb 02, Jan 02

**Comment by mrkwanzaa** [comment]
Reopening this to allow for exceptions to be specified in the API

**Comment by mrkwanzaa** [comment]
I've added the `orderingWithParent` key which can be set to false to stop that level and any children from looking at orderings above the specified level. See the example below or kitchen_sink.py

```
"state": {
                            "name": "States",
                            "parent": "country",
                            "ordering": ["Michigan", "Florida", "Indiana", "Massachusetts", "Ontario"],
                            "orderWithParent": False, # True if not specified
                        },
```
