### ISSUE TITLE
Implement informative label or component for empty chart data

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#479]
As indicated here:

https://github.com/MIT-CAVE/cave_static/blob/76456bba888ddecbd338e534c5147ee88c7e1db3/src/ui/views/dashboard/DashboardChart.js#L185C1-L187

**Comment by connor-makowski** [comment]
NIce job @brianzheng205 closing with https://github.com/MIT-CAVE/cave_static/commit/0d455af15198cce9c0b50a60342b39fdd2d1d992
