### ISSUE TITLE
Use websockets for all connections from cave_static to cave_app ?

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#48]
I am considering using websockets inside of cave_static to do all communications out to cave_app over a single connection using a simple messaging framework.

Currently all requests are post requests sending data and returning simple success responses while all actual data flows back over the websocekt. It just feels a bit silly to open a ton of connections when we already have a socket in place.

Just initial my initial thoughts here. Trying to get your opinions.

**Comment by luisvasq** [comment]
This makes sense to me. :+1:

**Comment by connor-makowski** [comment]
Okay. I will go ahead and close this out and make an epic for this one.
