### ISSUE TITLE
Drag 'n Drop and Resizing Capabilities for Charts

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#489]
@katherineyli: more info to follow...

**Comment by luisvasq** [comment]
To support this feature, we can add a new dependency: [`react-grid-layout`](https://github.com/react-grid-layout/react-grid-layout).

About resizing, one initial consideration is setting a minimum size constraint for a chart view. Maybe `react-grid-layout` offers support for that through built-in props, but if not, we can handle it through an event.

For now, we'll keep it local (`useState`), but I talked to Connor earlier and he might want to sync it with the API, so we can easily add support for that later.

@connor-makowski, do you have any additional thoughts or requirements about this new feature?

**Comment by connor-makowski** [comment]
@luisvasq were does this currently stand?
