### ISSUE TITLE
Remove Map Time Controls

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#493]

**Comment by connor-makowski** [comment]
This should be removed as part of a 2.2.1 release as this time control is buggy.

**Comment by luisvasq** [comment]
@connor-makowski, just confirming that you want to remove the time control from the map? I could look into a possible fix.

**Comment by connor-makowski** [comment]
No, the floating modal is where everything should be done anyway. This should have been removed during the floating modal add.
