### ISSUE TITLE
Overhaul Map Legend UI/UX

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#499]

**Comment by connor-makowski** [comment]
- [ ] Redesign UI / UX
- [ ] Create a super compact version
- [ ] Create a more complete version
- [ ] Control all map interactions via a modal

**Comment by luisvasq** [comment]
The mini legend should be fully functional, except for the color picker, icon selector, and size controls, which are still pending. I haven't found a third-party color picker with a nice UI/UX, so I'm considering whether we should build it from scratch. In the meantime, I'm going to go ahead and integrate these changes into `3.0.0-dev` while @ellawang9 and I figure out the rest.

**Comment by luisvasq** [comment]
The functionality is now complete. We can improve the UI/UX a bit more, but this should offer a solid upgrade! Thanks to @ellawang9  for her ground work on the size and height (disabled for now) sections, as well as migrating the classic legend to MUI v6.
