### ISSUE TITLE
`1.0.0`

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#51]
Creating this issue to keep track of breaking changes as we move towards `1.0.0`

- #50
- #52
- #73

Please, feel free to add any issues containing breaking changes to this list.

**Comment by connor-makowski** [comment]
Instead of logging them, here we should appropriate the tickets to the epic #87

**Comment by luisvasq** [comment]
Makes sense. Just attached #50 to #87. Closing now.
