### ISSUE TITLE
Optimize number input update

### ISSUE THREAD

**Issue by brianzheng205** [MIT-CAVE/cave_static#523]
The number input currently waits for the server to update its value locally, which causes a slight, undesirable update.

**Comment by brianzheng205** [comment]
@connor-makowski Should I go ahead and start working on this?

**Comment by brianzheng205** [comment]
@connor-makowski I updated it to first use the new value locally and update the value if necessary once the server changes `defaultValue`.

**Comment by connor-makowski** [comment]
Is there a PR or commit hash that you can link here?

**Comment by brianzheng205** [comment]
https://github.com/MIT-CAVE/cave_static/commit/b3ff6ee336b6a87dc8788be2b6677e03cd2b8b3f

**Comment by connor-makowski** [comment]
See PR: https://github.com/MIT-CAVE/cave_static/pull/530
