### ISSUE TITLE
Allow downloading the grouped / aggregated data from a chart

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#528]
This should be a CSV and would be the data as it would be presented if it were a table chart.

**Comment by connor-makowski** [comment]
@brianzheng205 can you prioritize this as pure front end code?

**Comment by brianzheng205** [comment]
@connor-makowski @mrkwanzaa this is done in https://github.com/MIT-CAVE/cave_static/pull/561.
