### ISSUE TITLE
State Cleanup and Pane Behavior for Virtual Keyboard

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#531]
Hi Brian,

After a deeper look, I'm logging a couple of items for the virtual keyboard that we should take care of:

- [x] Remove the duplicate `keyboard` group at the root of the Redux state
- [x] Keep the pane(s) open while typing on the virtual keyboard or simply when it is displayed. (We should probably handle this in `handlePaneClickAway`.)

Could you check these and let me know if you have any questions?

Thanks!

**Comment by brianzheng205** [comment]
@luisvasq Both should be taken care of. https://github.com/MIT-CAVE/cave_static/commit/196142bed29c1a2231d53176ed084be1e9165970
