### ISSUE TITLE
Delete Session dialog appears behind the pane

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#557]
Let's make sure the dialog is displayed in front.

![Image](https://github.com/user-attachments/assets/06639930-4989-4981-a9f5-671e0c17b7e6)

**Comment by luisvasq** [comment]
Similarly, let's work on this under a `3.0.0-dev-*` branch.

**Comment by connor-makowski** [comment]
I expect this may already be fixed?

**Comment by brianzheng205** [comment]
@connor-makowski @luisvasq https://github.com/MIT-CAVE/cave_static/pull/586

**Comment by luisvasq** [comment]
LGTM! Merging now.
