### ISSUE TITLE
The Duplicate action for Current Session in Sessions Pane doesn't work

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#558]

**Comment by brianzheng205** [comment]
@luisvasq @connor-makowski Caused by flickering bug so the form for creating the duplicate session wouldn't be visible and you couldn't scroll down to it. Scroll bar would also not show up in some scenarios. Resolved in https://github.com/MIT-CAVE/cave_static/pull/579.

**Comment by luisvasq** [comment]
Thanks, @brianzheng205! Those bugs were annoying.
