### ISSUE TITLE
Upgrade MUI to v6 and handle breaking changes

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#559]
We'd need to handle breaking changes, migration steps, and deprecated APIs:

- [ ] Identify and fix any breaking changes introduced in MUI v6
- [ ] Handle deprecated props / components / features and replace them with the updated alternatives
- [ ] Test the functionality to ensure it remains the same after the upgrade

Refs:
- https://mui.com/material-ui/migration/upgrade-to-v6/
- https://mui.com/material-ui/migration/migrating-from-deprecated-apis/

**Comment by luisvasq** [comment]
Using the official codemod(s) is fine, but let's make sure to run `npm run lint` afterwards.

**Comment by luisvasq** [comment]
To support some updates in #499, I've upgraded MUI to v6. So far, I haven't found any issues, but the tasks in the checklist should remain the same.

**Comment by luisvasq** [comment]
Nice job with `ClassicLegend`, @ellawang9! There's only one migration issue: getting the dropdowns to fill up the available space. I think this is related to finding `Grid2`'s equivalent of the [`Grid`'s `xs` prop when set to `true`](https://mui.com/material-ui/react-grid/#auto-layout).

![legend-issue](https://github.com/user-attachments/assets/c4fb4e78-ae74-41d4-acbe-fca8a31fe8c5)

**Comment by ellawang9** [comment]
Thanks for pointing this out, Luis! Should be fixed now.
<img width="335" alt="image" src="https://github.com/user-attachments/assets/0f8ff6a8-1eb6-4b67-98b6-fd12e6db0314">
