### ISSUE TITLE
Fix session naming bug for new sessions

### ISSUE THREAD

**Issue by brianzheng205** [MIT-CAVE/cave_static#567]

**Comment by brianzheng205** [comment]
@connor-makowski @mrkwanzaa I fixed the bug. Accidentally pushed to [3.0.0-dev](https://github.com/MIT-CAVE/cave_static/tree/3.0.0-dev), but hopefully that should be fine since I only changed a few lines.

**Comment by connor-makowski** [comment]
Should be fine.
