### ISSUE TITLE
Flickering while scrolling through session list

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#577]
When scrolling through the session list, there's a bit of "inertia"... the scroll position jumps back to a previous spot, as shown below. I also noticed that, despite the flickering, you can scroll down, but the scrollbar isn't visible.

@aiizhao, I know you tackled this issue in #544. Can you still reproduce this flickering behavior? Connor mentioned that Brian is currently working on sessions, so maybe @brianzheng205 could take a look... it might also help avoid merge conflicts if we attempt a fix now.

![Image](https://github.com/user-attachments/assets/9d60a64d-f1d4-49a7-b25a-9788e993236e)

**Comment by brianzheng205** [comment]
Yea I also noticed flickering while working on session panes. I can look into this.
