### ISSUE TITLE
Crashing when mapFeature data is empty

### ISSUE THREAD

**Issue by mrkwanzaa** [MIT-CAVE/cave_static#592]
To recreate, just set valuelists and location lists to be empty for any mapFeature. I have found related bugs in `MinimalLegend.js`, `useMapFilter.js`, `ColorLegend.js`, and `SizeLegend.js` (Maybe more). @luisvasq I am happy to fix these, just let me know when a good time for me to modify these files is.

**Comment by luisvasq** [comment]
Thanks for looking into this, Willem. I don't have any pending changes on those files, so please feel free to take over and lmk if you need help with any bug/issue.
