### ISSUE TITLE
Waterfall Chart Support 

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#61]
This should operate exactly the same as stacked bar charts except, each subsequent item in the chart should start at the point that the previous item ends with the first item starting at 0.

![waterfall.png](https://images.zenhubusercontent.com/5cab69cc3afb1e4d31f957da/c64f33b1-a7a1-4506-b31e-6bfa185214d4)

Ordering of the bars will be the exact same as for the stacked bar chart too. This is already handled in the `categories.data.customkey.nestedStructure` process so no change is needed here.

An example idea of what this should look like is here: https://echarts.apache.org/examples/en/editor.html?c=bar-waterfall

Note: Our charts do not need to end at 0 like the example.

@luisvasq this is yours to own, but I want @Visionnaire19 to get some exposure here as well. Work with him as you work through this issue.

**Comment by connor-makowski** [comment]
Assigning to @Visionnaire19

**Comment by connor-makowski** [comment]
@luisvasq Can you help him as he will take ownership of this as his first solo issue.

**Comment by luisvasq** [comment]
Sure thing. I'm happy to help Jean with this one. @Visionnaire19 I'll write you on Slack to set up a discussion about charts.

**Comment by connor-makowski** [comment]
![stacked_waterfall.png](https://images.zenhubusercontent.com/5cab69cc3afb1e4d31f957da/edbdbc21-43ef-4e7e-ad77-1b1deabab27d)

Looks great @luisvasq and @Visionnaire19

**Comment by connor-makowski** [comment]
Closing this out with: 

8c1e52f19e65c86977ec5894a5422b796ab53baa
2c1f2d627c720ac1524ab27ee8a83c66a8c2060d
7f1b32352274b25a5d5e3c187bd29d6840a7dc26
