### ISSUE TITLE
3D Flights Support

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#80]
Not sure if we want this, but I think it might be interesting. See the link.

https://echarts.apache.org/examples/en/editor.html?c=lines3d-airline-on-globe&gl=1

@mitrussell Any thoughts here?

**Comment by mitrussell** [comment]
I like it, but I would not do any work until we get money from AeroAstro. We don't really need it for any "normal" supply chain design work. Right?

**Comment by connor-makowski** [comment]
No, this is a bit irregular, but got me thinking. For most normal supply chain charts we are considering see #81 #78 and #82

**Comment by mitrussell** [comment]
Agreed – these others seems like functionality we had before that would be nice to get back and match the data we are already visualizing. The flight one seems specialized and worth waiting for the ask…

From: Connor Makowski ***@***.***>
Reply-To: MIT-CAVE/cave_static ***@***.***>
Date: Thursday, November 17, 2022 at 2:05 PM
To: MIT-CAVE/cave_static ***@***.***>
Cc: Tim Russell ***@***.***>, Assign ***@***.***>
Subject: Re: [MIT-CAVE/cave_static] 3D Flights Support (Issue #80)


No, this is a bit irregular, but got me thinking. For most normal supply chain charts we are considering see #81<https://github.com/MIT-CAVE/cave_static/issues/81> #78<https://github.com/MIT-CAVE/cave_static/issues/78> and #82<https://github.com/MIT-CAVE/cave_static/issues/82>
