### ISSUE TITLE
Implement new loading feature

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#91]
See: 

https://github.com/MIT-CAVE/cave_app/commit/2af55376a7e273be4f56bf782edd350d9aaff727
https://github.com/MIT-CAVE/cave_app/commit/7d119cc62b6143488a7b52c5e7d4e23e30d9a4a5

https://github.com/MIT-CAVE/cave_static/commit/be2a60c20098220e72230742e6bf36737ddef3d7

**Comment by mrkwanzaa** [comment]
I've implemented this static side, but it looks like the messages to show/hide from the `cave_app` are being received right after each other so the loader is never shown(even when the actual session data takes a few seconds to load). @connor-makowski do you want me to create a new issue for this or is it expected?

**Comment by connor-makowski** [comment]
Closing with 
https://github.com/mit-cave/cave_static/commit/d49e181352111e3cbd0f30faec92e79a3539af4b
and
https://github.com/mit-cave/cave_app/commit/1698302f01247f09b9ee8b0d6e827848169bcd7c
