### ISSUE TITLE
Improve Client Side Performance

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#93]
When data sizes get larger, the client side performance lags significantly.

To test this we will start using the `cave_api/src/cave_api/big_model/api`. 

See: https://github.com/MIT-CAVE/cave_app/commit/ddc927b28012e39a1c830dc3694c2f63adf1cd18 

At the above commit, I simply create 10,000 nodes spaced evenly (with a x=long y=lat projection) around lat 0 long 0.

You should expand the cave app api to test this for nodes, geos, arcs and stats as we work on this issue.

**Comment by connor-makowski** [comment]
A quick update. The UI for filters is particularly slow.

**Comment by mrkwanzaa** [comment]
Closing for 1.0.0
